# Generated by Django 5.0 on 2024-05-15 14:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Product', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ticket',
            name='prize_categories',
            field=models.CharField(),
        ),
    ]
