# Generated by Django 5.0 on 2024-05-15 15:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Product', '0002_alter_ticket_prize_categories'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ticket',
            name='prize_categories',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='ticket',
            name='title',
            field=models.TextField(),
        ),
    ]
