# Generated by Django 5.0 on 2024-03-31 16:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Product', '0002_ticket'),
    ]

    operations = [
        migrations.AddField(
            model_name='ticket',
            name='image_1',
            field=models.ImageField(default='default_image.jpg', upload_to='ticket_images/'),
        ),
        migrations.AddField(
            model_name='ticket',
            name='image_2',
            field=models.ImageField(default='default_image.jpg', upload_to='ticket_images/'),
        ),
        migrations.AddField(
            model_name='ticket',
            name='image_3',
            field=models.ImageField(default='default_image.jpg', upload_to='ticket_images/'),
        ),
    ]
