# Generated by Django 5.0 on 2024-04-02 08:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Product', '0003_ticket_image_1_ticket_image_2_ticket_image_3'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ticket',
            name='image_1',
            field=models.ImageField(upload_to='ticket_images/'),
        ),
        migrations.AlterField(
            model_name='ticket',
            name='image_2',
            field=models.ImageField(upload_to='ticket_images/'),
        ),
        migrations.AlterField(
            model_name='ticket',
            name='image_3',
            field=models.ImageField(upload_to='ticket_images/'),
        ),
    ]
