# Generated by Django 5.0 on 2024-04-02 08:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Product', '0004_alter_ticket_image_1_alter_ticket_image_2_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ticket',
            name='number_of_tickets',
            field=models.IntegerField(),
        ),
    ]
