# Generated by Django 5.0 on 2024-05-18 06:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Product', '0005_seller_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='seller',
            name='image',
            field=models.ImageField(upload_to='profile_images/'),
        ),
    ]
