# Generated by Django 5.0 on 2024-05-20 10:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Product', '0006_alter_seller_image'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='seller',
            name='date_created',
        ),
    ]
