# Generated by Django 5.0 on 2024-05-20 10:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Product', '0007_remove_seller_date_created'),
    ]

    operations = [
        migrations.AddField(
            model_name='seller',
            name='date_created',
            field=models.DateTimeField(auto_now_add=True),
            preserve_default=False,
        ),
    ]
