# Generated by Django 5.0 on 2024-05-20 11:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Product', '0008_seller_date_created'),
    ]

    operations = [
        migrations.AddField(
            model_name='ticket',
            name='date_createds',
            field=models.DateTimeField(auto_now_add=True),
            preserve_default=False,
        ),
    ]
