# Generated by Django 5.0 on 2024-05-22 11:53

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Product', '0009_ticket_date_createds'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ticket',
            name='seller',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='Product.seller'),
            preserve_default=False,
        ),
    ]
