# Generated by Django 5.0 on 2024-07-01 16:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Product', '0011_ticket_fully_purchased_at_ticket_winner_drawn_winner'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Winner',
        ),
    ]
