# Generated by Django 5.0 on 2024-07-01 18:34

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Product', '0013_winner'),
        ('PurchasedTicket', '0002_rename_tcket_nmber_purchasedticket_ticket_number'),
    ]

    operations = [
        migrations.AddField(
            model_name='winner',
            name='Ticket_number',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='PurchasedTicket.purchasedticket'),
            preserve_default=False,
        ),
    ]
