# Generated by Django 5.0 on 2024-07-19 20:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Product', '0014_winner_ticket_number'),
    ]

    operations = [
        migrations.AddField(
            model_name='winner',
            name='winner_name',
            field=models.CharField(default=1, max_length=50),
            preserve_default=False,
        ),
    ]
