# Generated by Django 5.0 on 2024-05-17 19:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('UserAccount', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='transaction',
            name='transaction_from',
            field=models.CharField(choices=[('from_chapa', 'From chapa'), ('from_wallet', 'From your wallet')], max_length=20, null=True),
        ),
    ]
