# Generated by Django 5.0 on 2024-05-21 23:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('UserAccount', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transaction',
            name='transaction_from',
            field=models.CharField(max_length=20, null=True),
        ),
    ]
