# Generated by Django 5.0 on 2024-05-17 14:02

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Comments', '0001_initial'),
        ('Product', '0003_alter_ticket_prize_categories_alter_ticket_title'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RenameModel(
            old_name='TicketCommentModel',
            new_name='TicketComment',
        ),
    ]
