# Generated by Django 5.0 on 2024-06-28 17:19

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Comments', '0002_rename_ticketcommentmodel_ticketcomment'),
        ('Product', '0006_alter_seller_image'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RenameModel(
            old_name='TicketComment',
            new_name='TicketCommentModel',
        ),
    ]
